### ISSUE TITLE
Modelica keywords

### ISSUE THREAD

**Issue by lochel** [modelica-tools/atom-language-modelica#19]
I think the keywords are not complete, `initial algorithm` is missing at least.
Also I am wondering why `register` is in the keyword list.

Is there more to fix?

**Comment by lochel** [comment]
I looked up all keywords and these are missing: `encapsulated`, `external`, `impure`, `in`, `inner`, `operator`, `outer`, `pure`, `return`, and `type`.

**Comment by thorade** [comment]
I did not know `pure` and `impure` were in the Spec already, but if you looked it up then you are informed much better.
Is having `initial`, `equation` and `algorithm` sufficient or do composite keywords like `initial algorithm` have to be listed separately?
If there is no further discussion I would just accept your PR tomorrow (or you can do it yourself).

**Comment by tshort** [comment]
+1

**Comment by lochel** [comment]
`initial` is listed additionally as composite keyword since it should be displayed differently if it is used as function call or preamble of an initial equation/algorithm section.

**Comment by thorade** [comment]
Who will run `apm publish patch` ?

**Comment by thorade** [comment]
OK, I published `v0.3.1`
