### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thorade** [modelica-tools/atom-language-modelica#2]
Could you specify under what license your code is available by adding a `LICENSE.md` file?
https://help.github.com/articles/open-source-licensing/
http://choosealicense.com/

Atom itself and all packages by github are licensed under MIT, 
so you might want to choose that license, too.
https://atom.io/faq
http://choosealicense.com/licenses/mit/

**Comment by raphaelchenouard** [comment]
MIT Licence added
